### PR TITLE
Initial cards

### PR DESCRIPTION
**Pull request by triggrhappy0**

### CODE REVIEW

**Comment by brooks42** [comment]
Does Aeroblast need to say "put three cards you own in exile on the bottom of your library _in any order_?

**Comment by brooks42** [comment]
Should Barrier have the line break? It's only one ability

**Comment by brooks42** [comment]
Bayleef says something different than Populate's current reminder text in Gatherer. Should say "(Create a token that’s a copy of a creature token you control.)"?

**Comment by triggrhappy0** [comment]
> Does Aeroblast need to say "put three cards you own in exile on the bottom of your library _in any order_?

I don't think so, see Valukut Awakening. Odd that they're inconsistent about it, but adding "in any order" adds a line so I say we stick with it.

**Comment by triggrhappy0** [comment]
> Should Barrier have the line break? It's only one ability

I think you're right, I was basing it off Faith's Shield, which breaks them apart for Fateful Hour, like metalcraft. Fixed.

**Comment by triggrhappy0** [comment]
> Bayleef says something different than Populate's current reminder text in Gatherer. Should say "(Create a token that’s a copy of a creature token you control.)"?

Yeah it's intentionally shorter. Reminder text is whatever we want it to be basically.

**Pull request merged**
